### ISSUE TITLE
include ES 2.0 in travis testing env

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#453] opened 2015-10-30 09:24 UTC
Right now we are using only simpel elasticsearch service provided from travis. Lets include custom ES versions the latest 1.* and 2.*

**Comment by kazgurs** [comment] 2015-12-18 09:57
Installing it with environment build [matrix](https://github.com/kazgurs/ElasticsearchBundle/blob/master/.travis.yml#L8-L11) . Downside - have to use specific ES versions. Currently, 2.0.2 and 2.1.1 are failing. Hanging on to PR for now, in case the issue is fixed within the bundle to allow the build to succeed.

**Closed** 2015-12-29 07:15 UTC
Labels: qa
